[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "droll"
version = "0.1"
authors = [
    {name = "Rhys Ulerich"},
]
description = "Implementation of game mechanics for Dungeon Roll"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
]

[project.optional-dependencies]
dev = [
    "flake8",
    "Sphinx",
]

[project.scripts]
droll = "droll.__main__:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["droll*"]

[tool.setuptools.package-data]
"*" = ["*"]
